server:
  port: 8080
spring:
  redis:
    password: ****
    cluster:
      nodes: 192.168.1.1:8001,192.168.1.1:8002
      max-redirects: 3
    timeout: 10000
    lettuce:
      pool:
        max-active: 20 # 连接池最大连接数，负值没有限制
        max-idle: 10 # 最大空闲连接数，负值没有限制
        min-idle: 0 # 保持最小空闲连接数
        max-wait: 1000ms # 连接池最大阻塞等待时间，使用负值无限期阻止
        time-between-eviction-runs: 1 # 空闲对象逐出器线程的运行间隔时间
      cluster:
        refresh:
          adaptive: true # 开启自适应更新集群拓扑视图
          period: 10000 # 拓扑刷新周期（ms）
          dynamic-refresh-sources: true # 是否允许动态刷新拓扑资源
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DATASOURCE_URL:jdbc:mysql://localhost:3306/redis_test?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8}
    username: ${DATASOURCE_USERNAME:root}
    password: ${DATASOURCE_PASSWORD:Jabez2020}
mybatis:
  configuration:
    mapUnderscoreToCamelCase: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

