server:
  port: 8082
spring:
  kafka:
    consumer:
      bootstrap-servers: 192.168.226.133:9091,192.168.226.133:9092,192.168.226.133:9093
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
