name: Create PR and Merge Feature Branch
on:
  push:
    branches:
      - feature/*

jobs:
  create-pr-and-merge:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        ref: master
        token: ${{ secrets.GITHUB_TOKEN }}
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install Git
      run: |
        sudo apt-get update
        sudo apt-get install -y git
    - name: Create PR
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git checkout -b feature/update_boot_version
        git pull --rebase origin feature/update_boot_version
        git push origin feature/update_boot_version
        gh pr create --title "Merge feature branch to master" --body "This PR merges the feature branch to master." --base master --head feature/update_boot_version
      env:
        GITHUB_REF: feature/update_boot_version
    - name: Merge PR
      run: |
        gh pr merge --admin --delete-branch --squash feature/update_boot_version
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
