name: Merge Feature to Main

on:
  push:
    branches:
      - feature/*

jobs:
  merge-feature-to-main:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        ref: master
        token: ${{ secrets.GITHUB_TOKEN }}
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install Git
      run: |
        sudo apt-get update
        sudo apt-get install -y git
    - name: Merge feature branch to main
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git merge --no-ff feature/${{ github.event.repository.default_branch }}
        git push origin main
