name: Create PR and Merge Feature Branch
on:
  push:
    branches:
      - feature/*

jobs:
  create-pr-and-merge:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        ref: master
        token: ${{ secrets.GITHUB_TOKEN }}
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install Git & jq
      run: |
        sudo apt-get update
        sudo apt-get install -y git
        sudo apt-get install -y jq
    - name: Create PR
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git fetch origin feature/update_boot_version
        git checkout feature/update_boot_version
        pr_info=$(curl -H "Authorization: token $GH_TOKEN" -X POST -d '{"title":"Merge feature branch to master","body":"This PR merges the feature branch to master","base":"master","head":"feature/update_boot_version"}' https://api.github.com/repos/$GITHUB_REPOSITORY/pulls)
        pr_number=$(echo $pr_info | jq -r '.number')
        echo "::set-output name=pr_number::$pr_number"
      env:
        GITHUB_REF: feature/update_boot_version
        GH_TOKEN: ${{ github.token }}
      id: create-pr
    - name: Add Approvers
      run: |
        gh pr edit $PR_NUMBER --add-reviewer "zmsoft" --add-reviewer "zbc0512"
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PR_NUMBER: ${{ steps.create-pr.outputs.pr_number }}
    - name: Wait for approval
      run: |
        while true; do
          status=$(gh pr view $PR_NUMBER --json reviews | jq -r '.reviews[] | select(.state == "APPROVED")')
          if [ "$status" != "" ]; then
            break
          fi
          sleep 60
        done
    - name: Merge PR
      run: |
        sleep 5
        git checkout master && git fetch origin master && git merge  feature/update_boot_version
        git push origin master
        
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
