name: workspace deployment

on:
  push:
    branches: 
      - workspace_publish
      
jobs:
  release:
    runs-on: ubuntu-latest
    steps: 
    - name: Manual Workflow Approval
    - uses: trstringer/manual-approval@v1.9.0
      with:
        # Required approvers
        approvers: 'zmsoft'
        # Secret
        secret: '123456'
        minimum-approvals: ''
        # The custom subtitle for the issue
        issue-title: 'PR Approval'
        issue-body: 'PR Approval'
        exclude-workflow-initiator-as-approver: ''
        additional-approved-words: '' 
        additional-denied-words: '' 
          
    - name: Synapse workspace deployment
    - uses: actions/checkout@v2
    - uses: azure/synapse-workspace-deployment@V1.9.0
      with:
        TargetWorkspaceName: 'target workspace name'
        TemplateFile: './path of the TemplateForWorkspace.json'
        ParametersFile: './path of the TemplateParametersForWorkspace.json'
        OverrideArmParameters: './path of the parameters.yaml'
        environment: 'Azure China'
        resourceGroup: 'target workspace resource group'
        clientId: ${{secrets.CLIENTID}}
        clientSecret:  ${{secrets.CLIENTSECRET}}
        subscriptionId: 'subscriptionId of the target workspace'
        tenantId: 'tenantId'
        DeleteArtifactsNotInTemplate: 'true'
        managedIdentity: 'False'
          
